Repository jra457/Group-6, pull requests merged in 2023-05, with the labels that each got.

#92 Profile and Registration validation
  groupSix/db.sqlite3
  groupSix/knockoffKing/__pycache__/admin.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/models.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/tests.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/views.cpython-310.pyc
  groupSix/knockoffKing/admin.py
  groupSix/knockoffKing/migrations/0016_remove_shippinginfo_streetname_and_more.py
  groupSix/knockoffKing/migrations/0017_remove_shippinginfo_customer_shippinginfo_user.py
  groupSix/knockoffKing/migrations/0018_alter_shippinginfo_zipcode.py
  groupSix/knockoffKing/migrations/0019_alter_shippinginfo_state.py
  groupSix/knockoffKing/migrations/0020_remove_shippinginfo_shippingcost.py
  groupSix/knockoffKing/migrations/__pycache__/0016_remove_shippinginfo_streetname_and_more.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0017_remove_shippinginfo_customer_shippinginfo_user.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0018_alter_shippinginfo_zipcode.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0019_alter_shippinginfo_state.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0020_remove_shippinginfo_shippingcost.cpython-310.pyc
  groupSix/knockoffKing/models.py
  groupSix/knockoffKing/templates/knockoffKing/order_detail.html
  groupSix/knockoffKing/templates/knockoffKing/orders.html
  groupSix/knockoffKing/templates/knockoffKing/profile.html
  groupSix/knockoffKing/templates/knockoffKing/register.html
  groupSix/knockoffKing/tests.py
  groupSix/knockoffKing/views.py
Labels: Back-End, Front-End

#93 Views.py Cleanup and Product Validation
  groupSix/db.sqlite3
  groupSix/knockoffKing/__pycache__/urls.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/views.cpython-310.pyc
  groupSix/knockoffKing/templates/knockoffKing/cart.html
  groupSix/knockoffKing/templates/knockoffKing/home.html
  groupSix/knockoffKing/templates/knockoffKing/index.html
  groupSix/knockoffKing/templates/knockoffKing/nav_admin.html
  groupSix/knockoffKing/templates/knockoffKing/nav_customer.html
  groupSix/knockoffKing/templates/knockoffKing/nav_guest.html
  groupSix/knockoffKing/templates/knockoffKing/nav_main.html
  groupSix/knockoffKing/templates/knockoffKing/nav_seller.html
  groupSix/knockoffKing/templates/knockoffKing/orders_customer.html
  groupSix/knockoffKing/templates/knockoffKing/orders_seller.html
  groupSix/knockoffKing/templates/knockoffKing/product_detail.html
  groupSix/knockoffKing/templates/knockoffKing/products.html
  groupSix/knockoffKing/templates/knockoffKing/store.html
  groupSix/knockoffKing/urls.py
  groupSix/knockoffKing/views.py
Labels: documentation, Back-End, Front-End

#98 Added Seller authentication
  groupSix/db.sqlite3
  groupSix/knockoffKing/__pycache__/models.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/views.cpython-310.pyc
  groupSix/knockoffKing/migrations/0021_seller_authenticated_by_admin.py
  groupSix/knockoffKing/migrations/0022_rename_authenticated_by_admin_seller_authenticated.py
  groupSix/knockoffKing/migrations/__pycache__/0021_seller_authenticated_by_admin.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0022_rename_authenticated_by_admin_seller_authenticated.cpython-310.pyc
  groupSix/knockoffKing/models.py
  groupSix/knockoffKing/templates/knockoffKing/products.html
  groupSix/knockoffKing/templates/knockoffKing/profile.html
  groupSix/knockoffKing/views.py
Labels: Back-End, Front-End

#100 Fixed price issue on checkout
  groupSix/db.sqlite3
  groupSix/knockoffKing/__pycache__/urls.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/views.cpython-310.pyc
  groupSix/knockoffKing/templates/knockoffKing/checkout.html
  groupSix/knockoffKing/templates/knockoffKing/checkout_success.html
  groupSix/knockoffKing/templates/knockoffKing/home.html
  groupSix/knockoffKing/urls.py
  groupSix/knockoffKing/views.py
Labels: Front-End

#99 Create Admin Test Cases
  groupSix/db.sqlite3
  groupSix/groupSix/__pycache__/__init__.cpython-310.pyc
  groupSix/groupSix/__pycache__/settings.cpython-310.pyc
  groupSix/groupSix/__pycache__/urls.cpython-310.pyc
  groupSix/groupSix/__pycache__/wsgi.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/__init__.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/admin.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/apps.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/models.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/tests.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/urls.cpython-310.pyc
  groupSix/knockoffKing/__pycache__/views.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0001_initial.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0002_seller_name.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0003_alter_seller_options_alter_usermodel_options.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0004_seller_nameslug.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0005_orderitem_order_items.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0006_orderhistory_delete_orderdetails.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0007_remove_orderhistory_price_and_more.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0008_order_sellers.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0009_seller_income.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0010_alter_seller_income.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0011_seller_prevwithdraw_withdrawhistory.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0012_transactions_delete_withdrawhistory.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0013_transactions_category.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0014_alter_transactions_category.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0015_orderitem_returnquantity_alter_orderitem_quantity.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0016_remove_shippinginfo_streetname_and_more.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0017_remove_shippinginfo_customer_shippinginfo_user.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0018_alter_shippinginfo_zipcode.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0019_alter_shippinginfo_state.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/0020_remove_shippinginfo_shippingcost.cpython-310.pyc
  groupSix/knockoffKing/migrations/__pycache__/__init__.cpython-310.pyc
  groupSix/knockoffKing/models.py
  groupSix/knockoffKing/templatetags/__pycache__/__init__.cpython-310.pyc
  groupSix/knockoffKing/templatetags/__pycache__/group_tags.cpython-310.pyc
  groupSix/knockoffKing/tests.py
Labels: Test Cases

#101 Fix images issue
  groupSix/knockoffKing/tests.py
Labels: Test Cases

#102 Fixed bug with seller creation in admin test
  groupSix/knockoffKing/__pycache__/tests.cpython-310.pyc
  groupSix/knockoffKing/tests.py
Labels: bug, Test Cases
